# Generated by Django 5.2 on 2025-04-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0003_initial'),
        ('schedules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tutor_prepod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tutorprepod'),
        ),
        migrations.AddField(
            model_name='loaddpgsg',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.discipline'),
        ),
        migrations.AddField(
            model_name='loaddpgsg',
            name='discipline_prepod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.disciplineprepod'),
        ),
        migrations.AddField(
            model_name='loaddpgsg',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.group'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.discipline'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.group'),
        ),
        migrations.AddField(
            model_name='loaddpgsg',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.subgroup'),
        ),
    ]
