# Generated by Django 5.2 on 2025-04-21 16:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('count_of_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('count_of_hours', models.IntegerField()),
                ('course_number', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('semestr_number', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birthday', models.DateField(auto_now_add=True)),
                ('date_die', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('offset_mark', models.CharField(blank=True, choices=[('зачёт', 'Зачёт'), ('не зачёт', 'Не зачёт')], max_length=10, null=True)),
                ('attendance', models.IntegerField(choices=[(1, 'Присутствовал'), (2, 'Отсутствовал по УП'), (3, 'Отсутствовал')])),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('number_semestr', models.IntegerField()),
                ('offset_mark_1', models.CharField(blank=True, choices=[('зачёт', 'Зачёт'), ('не зачёт', 'Не зачёт')], max_length=10, null=True)),
                ('offset_mark_2', models.CharField(blank=True, choices=[('зачёт', 'Зачёт'), ('не зачёт', 'Не зачёт')], max_length=10, null=True)),
                ('mark_1', models.IntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mark_2', models.IntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('count_of_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.discipline')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateField()),
                ('date_fill', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('homework', models.TextField(blank=True, null=True)),
                ('comment_for_lessons', models.TextField(blank=True, null=True)),
                ('journal_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.journalpage')),
            ],
        ),
    ]
