# Generated by Django 5.2 on 2025-04-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='load_dpgsg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.loaddpgsg'),
        ),
        migrations.AddField(
            model_name='progressstudent',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.lesson'),
        ),
    ]
