# Generated by Django 5.2 on 2025-04-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressstudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.discipline'),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='journal_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.journalpage'),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='theme',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.discipline'),
        ),
        migrations.AddField(
            model_name='contenttheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.theme'),
        ),
    ]
