# Generated by Django 5.2 on 2025-05-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplineprepod',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutorprepod',
            name='id',
        ),
        migrations.AddField(
            model_name='disciplineprepod',
            name='date_input',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineprepod',
            name='date_output',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplineprepod',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='disciplineprepod',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='disciplineprepod',
            name='middle_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='disciplineprepod',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutorprepod',
            name='date_input',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprepod',
            name='date_output',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprepod',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tutorprepod',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tutorprepod',
            name='middle_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tutorprepod',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplineprepod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorprepod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
