# Generated by Django 5.2 on 2025-05-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_disciplineprepod_id_remove_tutorprepod_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplineprepod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='disciplineprepod', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
