# Generated by Django 5.2 on 2025-05-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_disciplineprepod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
